#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Must specify a filename"
    exit 1
fi

ps -ef | grep [s]office >/dev/null 2>/dev/null
if [[ $? -eq 0 ]]; then
    echo "This script cannot be run while LibreOffice is running."
    exit 2
fi

CONFIG=tidy_options.conf
BASE="$(basename "$1" .odt)"
soffice --invisible --convert-to htm:HTML --outdir html "$1"
tidy -q -config $CONFIG -f "html/$BASE.err" -i "html/$BASE.htm" | sed 's/ class="c[0-9]*"//g' > "html/$BASE.html"
cat "html/$BASE.html"

xsel -ib < html/"$BASE".html
echo 'File converted and copied to the clipboard.'
rm "html/$BASE.html" "html/$BASE.htm"
