#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Must specify a filename"
    exit 1
fi

ps -ef | grep [s]office >/dev/null 2>/dev/null
status=$?
if [[ $status -eq 0 ]]; then
    echo "This script cannot be run while LibreOffice is running."
    exit 2
fi

BASE="$(basename "$1" .odt)"
soffice --invisible --convert-to txt --outdir txt "$1"
./sermons_to_dynalist.py --infile="txt/$BASE.txt" --type=text --outfile="txt/$BASE.txt" --force
xsel -ib < "txt/$BASE.txt"
echo 'File converted and copied to the clipboard.'
rm "txt/$BASE.txt"
